### PR TITLE
Made Building happen async and in multiple process

### PR DESCRIPTION
**Pull request by beef331**
Prior to this on my machine building the docs for nimibook took roughly around 30s it now takes around 10s. For Norm's docs it went from around 60s down to around 30s. No clue if this is an overly interesting thing, just seen the easy ability to speed it up a bit so thought I wouldd make a PR

### CODE REVIEW

**Comment by beef331** [comment]
It's probably fine now, there were issues with it prior that I realized after

**Comment by pietroppeter** [comment]
sorry about letting this sit here so long, last two/three months I had very little time for nim stuff. I have a bit of backlog to catch up now but realistically I should be able to look and merge (along with a new release of nimibook) by the end of July (last words...).

**Comment by beef331** [comment]
It's fine by me it was like less than an hour of work so it's not a big deal.

**Comment by pietroppeter** [comment]
thanks for this! had time to check it out and it does indeed work as expected. Will now merge and work on documenting last changes and adding netlify preview before releasing 0.3

**Pull request merged**
