### PR TITLE
add class="active" logic

### PR DESCRIPTION
**Pull request by HugoGranstrom**
This code uses a lambda `parse_active` to decide whether or not a link is linking to the current page (active) or not.

### CODE REVIEW

**Comment by pietroppeter** [comment]
Hi this could work but it would anyway require a separate mechanism to create the toc.mustache, right?

I have an alternative approach based on fixed mustache templates and which needs another piece to be complete, see a write up here: https://pietroppeter.github.io/nblog/drafts/toc_mustache.html

the missing piece (as mentioned in the blogpost) is a way to parse the SUMMARY.md file into a json and set is_active = true in the correct place. I will probably stop here for a moment, and pick it up later, but if you feel like you can pick it up too.

**Comment by HugoGranstrom** [comment]
Yes it would require a separate mechanism to create the toc.mustache file. But it's also an *automatic* separate mechanism. My main problem with a SUMMARY.md is that it requires manually editing it to include a new file and it could be hard to know if every file is actually included. But if we (optionally) can generate the JSON just from the folder structure then I'm all over the fixed template. It's a very elegant approach 😄

**Comment by pietroppeter** [comment]
ah yes, we could also optionally generate the json from folder structure. And it is likely much easier to implement. Actually the two mechanism can coexist. If summary.md does not exits it will look at folder structure.

My main issue with the folder structure is that it is not evident the order of stuff (does `walkDirRec` guarantees some kind of order or should I order later? do I want to number stuff? how do I exclude stuff?).

I like that the SUMMARY.md instead allows for some customization (insert name of parts, separators, toc structure independent from folder structure, ...).

And yet another option could be a summary.nim (or toc.nim), with some api to create the Json (or better, an object) accordingly.

**Comment by HugoGranstrom** [comment]
I've thought a bit more about this now and I think I'm just common in from a different point of view. For a book with chapters and all, you may want the flexibility that a `Summary.md` file can give you. You can name your files whatever you want and structure them in any way you want, you just have to write the structure in the markdown instead. My view comes from the fact that `getting-started` isn't as structured as a book where you know chapter 11 comes after chapter 12 and can easily check that all chapters are in. But some order is still required and I'm thinking of ways one could fix that in an automatic approach.

> ah yes, we could also optionally generate the json from folder structure. And it is likely much easier to implement. Actually the two mechanism can coexist. If summary.md does not exits it will look at folder structure.

Yes indeed, that's a good approach :)

> My main issue with the folder structure is that it is not evident the order of stuff (does walkDirRec guarantees some kind of order or should I order later? do I want to number stuff? how do I exclude stuff?).

Hmm that's a good question. The sensible thing to do would that it goes through them in alphabetic order. So numbering things would work but then we are back at having the problem of what happens if I want to add something in between these other files, now I have to change the number of everything after this. 

> I like that the SUMMARY.md instead allows for some customization (insert name of parts, separators, toc structure independent from folder structure, ...).

Oh yes for sure, that's a fantastic feature to have for those that need it. 

> And yet another option could be a summary.nim (or toc.nim), with some api to create the Json (or better, an object) accordingly.

THIS!!! With macros we could probably create a neat DSL for the Summary as well. Being able to tailor the generation to your own needs sounds like a powerful idea :D

**Comment by pietroppeter** [comment]
my initial thoughts on target api and structure: #2

**Pull request closed without merging**
