### PR TITLE
automatic toc and book generation

### PR DESCRIPTION
**Pull request by pietroppeter**
WIP

- [X] target structure and api (with alternatives) defined
- [X] implement basic (manual) toc api
- [X] task cleanbook
- [X] publish runs nim files
- [X] dump/load for toc
- [ ] publish creates toc.json
- [ ] render for toc
- [ ] nbPostInit consumes toc.json
- [ ] support for class active
- [ ] update README
- [ ] review and cleanup

moved out of scope for this PR:
- implement toc api for autogeneration
- support for SUMMARY.md? (mmh, not so needed after the api)
- md file support
- update content of book: it should become the guide to nimibook (at least update the structure)

### CODE REVIEW

**Comment by HugoGranstrom** [comment]
This approach seems really promising 😄 And it looks better visually to me than the `SUMMARY.md` does. Do you have anything in mind for the syntax
```nim
toc = newToc("book"):
  Chapter("basics/", "Basics") # Autogenerate sections from file/folders in basics folder
  Chapter("advanced/", "Advanced") # Autogenerate sections from file/folders in basics folder
  Chapter("cool/index.nim"): # Manual layout of sections
    Section("cool/cool_stuff.nim")
```
Where the first argument to chapter is a folder instead of a file? I think it might be a suitable syntax for the "partial-structure" I was talking about before. For the chapters defined this way it automatically creates the child sections and chapters from the file/folder structure like the automatic script would. This way one can add structure when it is important and ignore it when it is less so. What do you think?

**Comment by pietroppeter** [comment]
yes, I have in mind something like that! At the moment I am implementing the part without autogeneration but the idea for the api is that you can decide when you want content to be autogenerated or not. Let me push my WIP...

**Comment by HugoGranstrom** [comment]
Great to hear! And you seem to have come a long way already 🚀 

Saw your comments on inheritance in your latest commit and as much as I want to avoid it, when all your procs start with `case toc.kind` (or equivalent if's) it may be a better option to go down the inheritance road...

**Comment by pietroppeter** [comment]
I will take a break now, but it was a productive Sunday! 💪 

> it may be a better option to go down the inheritance road...

yeah, maybe I will leave that for a future refactoring... 😝

**Comment by HugoGranstrom** [comment]
A well earned break B) I'll probably won't have much time this week for coding but if I'll get some spare time I could see if I can get the automatic approach working :)

Haha sounds good, unnecessary to redo your work 😂

**Comment by Clonkk** [comment]
@pietroppeter I didn't realize you were made this much progress. 

I have code that generate a valid toc.mustache from a repository structure in my branch : https://github.com/Clonkk/nimiBook/tree/clonkk_devel .

I'm only missing the logic to choose the chapter Name displayed. I also separated ``src`` from ``books`` folder (and we can deal with Nimble warnings later).

**Comment by HugoGranstrom** [comment]
Wow, we are having so much code for this now. I'm glad I didn't write a third version 🤣

**Comment by Clonkk** [comment]
So I can now generate a toc.mustache using a ``seq[Entry]``.

```nim
type
  Entry = object
    title: string
    path: string
    levels: seq[int]
```

I wrote code that can ``walkDir`` and generate it for us from the Nim files inside ``books`` foldern but since ``łalkDir`` do not allow us to use a pre-determined order we end-up with files classed by inode order on the file system (which isn't good obviously).

After spending some times playing with it,  I think the best solution is to expose an API ``addEntry`` to construct the ``seq[Entry]``.

**Comment by pietroppeter** [comment]
> I have code that generate a valid toc.mustache from a repository structure in my branch

ok, I will look into that. Just for a brief look I already can tell that it is much simpler and efficient have plain entries and record inside the entries the levels, instead of the complex hierarchy of Containers and Content that I have. I like better your approach. :)

**Comment by HugoGranstrom** [comment]
> but since walkDir do not allow us to use a pre-determined order we end-up with files classed by inode order on the file system (which isn't good obviously).

Hmm okay, that sounds troublesome. So we have to order them ourselves if we want to use `walkDir`. But is it a problem if we don't care about the order? Or does it jump all around the place randomly between folders also? :O

**Comment by Clonkk** [comment]
> Hmm okay, that sounds troublesome. So we have to order them ourselves if we want to use walkDir. But is it a problem if we don't care about the order? Or does it jump all around the place randomly between folders also? :O

It won't be because we are not going to do that :laughing:  
The new idea is to expose an ``addEntry`` API and let the user construct its own tree rather than generating it from the file arborescence inside ``books`` folder. 

We need manual input for the name of the title anyway. So asking for manual input for the order of the file isn't far fetched IMO.
This would also means that only the order from the ``levels`` is important, not how the file are ordered in ``books`` folder.

Maybe later on, I'll revisit the code to generate an alphabetical order from ``books`` arborescence, but for now separating the two is the simplest solution.

**Comment by HugoGranstrom** [comment]
So no automatic TOC generation for lazy Hugos? 😱🤣 
If it is easy enough to write I'll maybe accept it 😝 

Jokes aside, you have a good point in that it's hard to have the title in the filename because one could want spaces in it. But I'm still of the opinion that it's worth it if it means someone making a PR to a repo forgets to add it to the TOC manually and it's not found in the book 🤔 So it's not that much about *order* to me, it's more about if the file *exists*, then it should be included in the book. An easy way to extend your approach is ```
if path isDir:
  # add automatically generated entries to this entry and all it's children. Levels and such are "inherited"
else:
  # do what you are doing now
```

**Comment by Clonkk** [comment]
This is more or less what the commented code on my branch does. 

My proposition is to freeze a manual system for now and I'll give another go at the generation in another PR.

**Comment by HugoGranstrom** [comment]
Oh, I only read the commits for some reason and `commented unused code` didn't spark my interest 🙃 

Sounds very sane! 😄👍

**Comment by pietroppeter** [comment]
will rebase this on top of #3, see comments there

**Comment by pietroppeter** [comment]
work here is merged in #6

**Pull request closed without merging**
