### PR TITLE
add highlight.js for markdown code blocks

### PR DESCRIPTION
**Pull request by HugoGranstrom**
This PR adds support for highlight.js highlighting of code blocks in markdown, as wanted for [Owlkettle's nimiBook](https://github.com/can-lehmann/owlkettle/pull/34). This PR depends on https://github.com/pietroppeter/nimib/pull/179 in nimib being merged first.

### CODE REVIEW

**Comment by HugoGranstrom** [comment]
> We need to bump also nimib dependencies right? (After we release nimib side, otherwise CI will fail). 

Good point! I think it grabs the newest release either way (all checks were green), but we should update the deps definetly. 

> Not sure if there is some place in docs that needs updating, basically it is a feature that comes directly from nimib...

I don't think so, this is as you say a nimib thing that nimiBook just uses .

**Comment by HugoGranstrom** [comment]
The nim code block at the bottom [here](https://eccbd557290f1c399e80--nimibook.netlify.app/content.html) is from a markdown code block. It's getting rendered correctly, but I'm getting warnings in the console that highlight.js can't find a language called Nim. But the fact that it renders it either way is promising. (I didn't get this error back in nimib...)

**Comment by HugoGranstrom** [comment]
It seems like mdBook had its own highlight.js bundled with it that was misbehaving. I have removed it now, but there seems to be some calls to deprecated functions in `book.js` that I will have a look at later if we can remove entirely.

**Comment by HugoGranstrom** [comment]
The warnings are now gone! Ready for review

**Comment by pietroppeter** [comment]
All good, let's goooo! :)

**Comment by pietroppeter** [comment]
Mmh, not too soon, trying to merge from mobile:

image

What was that change of GitHub token about? I will have to look from desktop

**Comment by HugoGranstrom** [comment]
Hmm that's weird :/ It's not just that apps aren't allowed to merge PRs that modify workflows? 

> What was that change of GitHub token about? I will have to look from desktop

It was to fix the rate limiting issue we've been having with [Jiro's action](https://github.com/jiro4989/setup-nim-action#basic-usage). I had it in nimib as well were the tests were red because they were terminated by rate limiting. The fix seems to have done something at least.

**Comment by pietroppeter** [comment]
well, yeah, from desktop no issues, so I guess app has its limits!

**Pull request merged**
